platform :ios, “9.0”
use_frameworks!
inhibit_all_warnings!

target 'TFReplAI_Example' do
  pod 'TFReplAI', :path => '../'
  pod 'Alamofire', '~> 3.4'

  target 'TFReplAI_Tests' do
    #inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
